config/routes.rb
Hunaforgot::Application.routes.draw do

  root :to => "notes#index"

  resources :notes

  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }

end

app/models/grape.rb
class Grape < ActiveRecord::Base
  attr_accessible :quantity
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
end

app/models/note_search.rb
require 'active_model'

class NoteSearch 
  include ActiveModel::Validations

  validates_presence_of :title

  attr_accessor :title

  def initialize(value)
    @title = value
  end

  include ActiveModel::Conversion
  def persisted? ; false ; end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :timeoutable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # protect_from_forgery
end

app/controllers/users/registrations_controller.rb
# coding: utf-8

class Users::RegistrationsController < Devise::RegistrationsController

  http_basic_authenticate_with :name => "tam33363", :password => "hunanahu"

  def new
    super
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hunaforgot</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="wrapper">

    <div id="header">
      <div id="logo">HunaForgot</div>

      <div id="user_navi">
        <% if user_signed_in? %>
          Signed in as <%= current_user.email %>
          <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
        <% else %>
          <%= link_to "Sign in", new_user_session_path %>
          
          <% if false %>
          # if you want to use sign up function, "add :registerable" on models/user.rb
          or <%= link_to "Sign up", new_user_registration_path %>
          <% end %>

        <% end %>
      </div>
    </div>

    <div id="content">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      
      <%= yield %>
    </div>

    <div id="footer"></div>
  </div>
</body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :my_id %><br />
    <%= f.text_field :my_id %>
  </div>
  <div class="field">
    <%= f.label :my_password %><br />
    <%= f.text_field :my_password %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<%= link_to 'New Note', new_note_path %>

<div id="search" class="section">
  <%= form_for(@note_search, :url => {:action => :index}, :method => :get) do |f| %>
    <%= f.label :title, 'Title' %>
    <%= f.text_field :title, :value => @note_search.title, :id =>'title' %>
    <%= f.submit I18n.t(:search_button) %>
  <% end %>
</div>

<div class="section">
<table class="general">
  <col id="title">
  <col id="user_id">
  <col id="password">
  <col id="url">
  <col class="cmd">
  <col class="cmd">
  <col class="cmd">
  <tr>
    <th>Title</th>
    <th>ID</th>
    <th>Password</th>
    <th>Link</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notes.each do |note| %>
  <tr>
    <td><%= note.title %></td>
    <td><%= note.my_id %></td>
    <td><%= note.my_password %></td>
    <td><a href="<%= note.url %>" target="_blank">Website</td>
    <td><%= link_to image_tag('magnifier.png', :alt=>'Show'), note %></td>
    <td><%= link_to image_tag('pencil.png', :alt=>'Edit'), edit_note_path(note) %></td>
    <td><%= link_to image_tag('trash.png', :alt=>'Destroy'), note, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

</div>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @note.title %>
</p>

<p>
  <b>Id:</b>
  <%= @note.my_id %>
</p>

<p>
  <b>Password:</b>
  <%= @note.my_password %>
</p>

<p>
  <b>Url:</b>
  <%= @note.url %>
</p>


<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>